version: '2.2'
services:
  wintercms:
    image: hiltonbanes/wintercms:php7.4-apache
    ports:
      - 8888:80
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - .:/var/www/html/plugins/mikp/sanctum/
    environment:
      - APP_DEBUG=true
      - COMPOSER_UPDATE=true
      - INIT_WINTER=true
      - CMS_ADMIN_PASSWORD=admin

      - DB_TYPE=mysql
      - DB_HOST=mariadb
      - DB_DATABASE=wintercms
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_PORT=3306

  mariadb:
    image: mariadb:10.4
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    environment:
      - MYSQL_DATABASE=wintercms
      - MYSQL_ROOT_PASSWORD=root
